name: NSE Automation

on:
  schedule:
    - cron: '*/2 3-4 * * 1-5'   # Every 2 mins (8:58 AM – 10:00 AM IST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas requests pytz

    - name: Run NSE script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python nse_script.py
